### PR TITLE
ENG-601: Add version number to branch name

### PR DESCRIPTION
**Pull request by soru23**

### CODE REVIEW

**Comment by calummoore** [comment]
Shall I close this now, as we decided not to go down that route right? @soru23

**Comment by soru23** [comment]
i think we actually need this one, to create a new branch with the updated code, but need to test if this will actually create a new PR or just update the existing one

**Comment by calummoore** [comment]
As discussed, let's see if we can get this working without having to append a version number to branch.

**Comment by soru23** [comment]
not needed

**Pull request closed without merging**
